### ISSUE TITLE
Dependencies in last release are too broad

### ISSUE THREAD

**Issue by dekellum** [dekellum/marked#1]
For example all of these, which leaked through from our private development days: 
``` toml
html5ever       = { version=">=0.25.1, <2.0" }
tendril         = { version=">=0.4.1,  <2.0", features=["encoding_rs"] }
encoding_rs     = { version=">=0.8.13, <2.0" }
```
